name: genezio workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repo 
        uses: actions/checkout@v4
      - name: use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build
      - name: generate keys
        run: ./generate_keys.sh
      - name: my-artifact
        uses: actions/upload-artifact@v4
        with:
          name: nest-app
          path: |
            .certs
            ./dist
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Download container react dist
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: |
            dist
            .certs
      - name: Display structure of downloaded files
        run: ls -R
      - uses: Genez-io/genezio-github-action@v3
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy backend
        working-directory: |
          dist
          .cert
        run: genezio deploy
