name: genezio workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build
      - name: Archive container react artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archive dist folder
          path: dist
          retention-days: 1
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Download container react dist
        uses: actions/download-artifact@v3
        with:
          name: build dist folder
          path: dist
      - uses: Genez-io/genezio-github-action@v3
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy backend
        working-directory: dist
        run: genezio deploy
