name: genezio workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Copy repo 
        uses: actions/checkout@v4
      - name: use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build
      - name: generate keys
        run: ./generate_keys.sh
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DB_URL: ${{ secrets.DB_URL }}
          envkey_API_PORT: ${{ vars.API_PORT}}
          envkey_PREFIX_PASSWORD: ${{ secrets.PREFIX_PASSWORD }}
          envkey_GENEZIO_TOKEN: ${{ secrets.GENEZIO_TOKEN }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: Display structure of downloaded files
        run: ls
      - name: print env
        run: cat .env
      - name: upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: ./dist
      - name: upload certs
        uses: actions/upload-artifact@v4
        with:
          name: certs-artifact
          path: ./certs
      - name: upload .env
        uses: actions/upload-artifact@v4
        with:
          name: env-artifact
          path: ./.env
          include-hidden-files: true
  deploy-backend:
    runs-on: ubuntu-latest
    environment: main
    needs: build
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - name: Download certs
        uses: actions/download-artifact@v4
        with:
          name: certs-artifact
          path: certs
      - name: Download .env
        uses: actions/download-artifact@v4
        with:
          name: env-artifact
          path: .
      - name: Remove Folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: /draft
      - name: Display structure of downloaded files
        run: ls
      - uses: Genez-io/genezio-github-action@v3
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy nestjs backend
        working-directory: ./
        run: genezio deploy --env .env
